### ISSUE TITLE
Stepper component in combination with Shadcn/ui Form component

### ISSUE THREAD

**Issue by LuisRosengarten** [damianricobelli/shadcn-stepper#8]
Hey there,
first of all I wanna thank you for this awesome component.
Currently I am breaking my head on implementing the stepper in combination with the shadcn form component.
I want to create a multi step form that has one <Form> component that handles the form state for all steps, but I cannot get this to work with the <Stepper> component.

Heres what I have done so far:
https://codefile.io/f/DXxaSS78bn

The Problem is that the state of the stepper component (active step) does not change if I call nextStep() in the handleNext() Function and the ui for hasCompletedAllSteps shows always even in the beginning

Is there a way to make this work?

**Comment by floreean** [comment]
+1

**Comment by scrawlerapp** [comment]
+1

**Comment by Mahizha-N-S** [comment]
npx shadcn-ui@latest add stepper
Selected components not found. Exiting.
Can anyone help me solve this error

**Comment by damianricobelli** [comment]
@LuisRosengarten The problem you are having is because you are using the useStepper hook outside the context of the provider, which in this case is the <Stepper> component. You need to use the stepper underneath the provider to have access to change values through the hook. You can see an example form in the repository --> https://github.com/damianricobelli/shadcn-stepper/blob/main/examples/stepper-form.tsx

I close this issue as my answer clearly indicates the problem and how to solve it

**Comment by Mahizha-N-S** [comment]
hi thank you for the reply,
my doubt is that if i try to add stepper from shadcn it says no component found,
that means does the shadcn still doesnt have stepper or anything else?
